---
ansible_ssh_private_key_file: REPLACE_ME
ansible_ssh_user: ec2-user

monit_services:
  - monit_aerospike:
    name: aerospike
    type: process
    target: /var/run/aerospike/asd.pid
    start: "/etc/init.d/aerospike start"
    stop: "/etc/init.d/aerospike stop"
    user: root

monit_webinterface_enabled: false

aerospike_collectd_sourcename: "{{ collectd_sourcename }}"
aerospike_collectd_use_librato: false

aerospike_aws_base_vars_file: inventory/group_vars/all.yml
aerospike_aws_stacks_directory: inventory/group_vars
aerospike_aws_use_librato: false
aerospike_aws_s3_bucket: aerospike-example-configs
aerospike_aws_s3_tags:
  Name: aerospike-example-configs
aerospike_aws_region: us-east-1
aerospike_aws_template: "roles/ThinkNear.aerospike-aws/files/cf_stack_ip_{{ aerospike_mesh_seed_addresses | length }}.json"
aerospike_aws_ami: ami-b6cbc0dc
aerospike_aws_route53_zone_name: REPLACE_ME
aerospike_aws_included_stacks:
  - aerospike_example
